; trainer data structure fields (see macros/scripts/maps.asm)
rsreset
DEF TRAINER_EVENT_FLAG_BIT            rb
DEF TRAINER_VIEW_RANGE                rb
DEF TRAINER_EVENT_FLAG_POINTER        rw
DEF TRAINER_BEFORE_BATTLE_TEXT_BANK   rb
DEF TRAINER_BEFORE_BATTLE_TEXT        rw
DEF TRAINER_AFTER_BATTLE_TEXT_BANK    rb
DEF TRAINER_AFTER_BATTLE_TEXT         rw
DEF TRAINER_END_BATTLE_TEXT_BANK      rb
DEF TRAINER_END_BATTLE_TEXT           rw
DEF TRAINER_STRUCT_SIZE EQU _RS
