db "2.7.4"

; wGameInternalVersion values
	const_def
	const INTERNAL_VERSION_ORIGINAL_GAME ; also any versions prior to 2.6.0
	const INTERNAL_VERSION_2_6_0 ; also 2.6.1
	const INTERNAL_VERSION_2_6_2 ; also 2.6.3
	const INTERNAL_VERSION_2_6_4
	const INTERNAL_VERSION_2_7_0
	const INTERNAL_VERSION_2_7_1
	const INTERNAL_VERSION_2_7_2
	const INTERNAL_VERSION_2_7_3
	const INTERNAL_VERSION_2_7_4

DEF CURRENT_INTERNAL_VERSION EQU INTERNAL_VERSION_2_7_4
