SafariZoneEastRestHouse_Script:
	jp EnableAutoTextBoxDrawing

SafariZoneEastRestHouse_TextPointers:
	def_text_pointers
	dba_const _SafariZoneEastRestHouseScientistText,    TEXT_SAFARIZONEEASTRESTHOUSE_SCIENTIST
	dba_const _SafariZoneEastRestHouseRockerText,       TEXT_SAFARIZONEEASTRESTHOUSE_ROCKER
	dba_const _SafariZoneEastRestHouseSilphWorkerMText, TEXT_SAFARIZONEEASTRESTHOUSE_SILPH_WORKER_M
