; PureRGBnote: ADDED: trainers in this location

UndergroundPathWestEast_Script:
	ld hl, UndergroundPathWestEastTrainerHeaders
	ld de, UndergroundPathWestEast_ScriptPointers
	ld bc, wUndergroundPathWestEastCurScript
	jp ExecuteCustomMapScriptInTable

UndergroundPathWestEast_ScriptPointers:
	def_script_pointers
	dw_const CheckFightingMapTrainers,              SCRIPT_UNDERGROUNDPATHWESTEAST_DEFAULT
	dw_const DisplayEnemyTrainerTextAndStartBattle, SCRIPT_UNDERGROUNDPATHWESTEAST_START_BATTLE
	dw_const EndTrainerBattle,                      SCRIPT_UNDERGROUNDPATHWESTEAST_END_BATTLE

UndergroundPathWestEast_TextPointers:
	def_text_pointers
	dba_const UndergroundPathWestEastTrainer1Text,  TEXT_UNDERGROUNDPATHWESTEAST_GENTLEMAN1
	dba_const UndergroundPathWestEastTrainer2Text,  TEXT_UNDERGROUNDPATHWESTEAST_GENTLEMAN2
	dba_const UndergroundPathWestEastTrainer3Text,  TEXT_UNDERGROUNDPATHWESTEAST_COOL_KID
	dba_const _GrimerEventGirlText,  TEXT_UNDERGROUNDPATHWESTEAST_BRUNETTE_GIRL

UndergroundPathWestEastTrainerHeaders:
	def_trainers 3
UndergroundPathWestEastTrainerHeader0:
	trainer EVENT_BEAT_UNDERGROUND_PATH_WEST_EAST_TRAINER_0, 0, _UndergroundPathWestEastBattleText1, _UndergroundPathWestEastEndBattleText1, _UndergroundPathWestEastAfterBattleText1
UndergroundPathWestEastTrainerHeader1:
	trainer EVENT_BEAT_UNDERGROUND_PATH_WEST_EAST_TRAINER_1, 0, _UndergroundPathWestEastBattleText2, _UndergroundPathWestEastEndBattleText2, _UndergroundPathWestEastAfterBattleText2
UndergroundPathWestEastTrainerHeader2:
	trainer EVENT_BEAT_UNDERGROUND_PATH_WEST_EAST_TRAINER_2, 0, _UndergroundPathWestEastBattleText3, _UndergroundPathWestEastEndBattleText3, _UndergroundPathWestEastAfterBattleText3
	db -1 ;end

UndergroundPathWestEastTrainer1Text:
	script_trainer UndergroundPathWestEastTrainerHeader0

UndergroundPathWestEastTrainer2Text:
	script_trainer UndergroundPathWestEastTrainerHeader1

UndergroundPathWestEastTrainer3Text:
	script_trainer UndergroundPathWestEastTrainerHeader2
