_CinnabarLabTradeRoomPosterText::
	text "Une photo d'un"
	line "groupe de"
	cont "scientifiques"
	cont "souriants près"
	cont "grande machine."
	para "Le texte en"
	line "dessous indique:"
	para "DR.FUJI et son"
	line "équipe achèvent"
	cont "la création du"
	cont "premier #MON"
	cont "entièrement"
	cont "synthétique,"
	cont "PORYGON."
	done
